### ISSUE TITLE
Very cool idea but

### ISSUE THREAD

**Issue by Zmove** [RomainMazB/octobercms-frontend-model-editor#1]
Hello,

I red the description of your AdminBar plugin and FrontEnd Model Editor plugin, I think it's a really nice initiative in order to facilitate life of our end users.

However, I have a small suggestion. I'm not big fan of having a new top level menu to manage the models you want to put in the adminBar. Imagine if all module do like that (responsive image, image resizer, etc.....) It can quickly become a nightmare. To me, it's a settings thing, and it should be deported to the settings menu of october CMS.

What do you think about that ?

Best regards,

**Comment by RomainMazB** [comment]
Hi @Zmove , thanks for the interest.

_I'll specifically talk about AdminBar below:_
I understand your worries, I had the same when I published the AdminBar.

For now no plugin like that is available on the marketplace so plugin's authors may not want to lose their time doing a custom toolbar for each of their plugin just to provide a shortcut to the plugin backend configuration. AdminBar provides an easy way to do it, so some authors may abuse and create many useless links, for example a "author's website link" or whatever they want.

I'm currently searching a way to avoid this problem. I'm convinced an admin bar could be useful to everyone:
 - plugin's authors who want to easily add useful shortcut
 - theme's authors who may want to add theme's configuration shortcut which is kind of hidden in back-end settings or maybe a "support/report bug link" to their theme which is accurate in front-end
 - end user who just want a Dashboard / Auth shortcuts as it is provided in WP natively

For now the idea I have in my mind would be to add to the admin bar a settings icon, next to the Dashboard link to provide a way to hide links who are abusive/unwanted by the user:
the plugins could still register into the init event to add their link, but it could be hidden if the end user doesn't want to see them.

This is the only way to avoid this. Feel free to submit any idea!
___________________________
_Now for the FrontEnd Model Editor:_
 I think it's only a theme's authors or website's owner tool but this plugin is useless for the plugin's authors:
the links are displayed only on some page/url, defined directly in the theme's folder, so the plugin's author can't guess them.

As an easy example to understand my mind:
If I'm creating a blog website, for sure the Rainlab\Blog\Post would be located at `example.com/my-first-post` .
If I'm creating a corporate website, the home would be a landing page and the blog posts would be located at `example.com/blog/my-first-post`

Even though many are doing the same structure (blog on the homepage), the url doesn't correspond to the page name: a page's file could be located into `/pages/long/useless/path/mypage.htm` and displayed at `example.com` home if it defined the proper url:
```
url = '/'
```
In this case, you'll need to tell to the FrontEnd Model Editor to display the wanted link(s) at the name page `long-useless-path-mypage`

So Rainlab.Blog couldn't guess the page's name where to display their links.

Knowing that, I hope this tool will be properly used to display appropriate link, for example a theme's author who work on a shopaholic theme may want to display shopaholic's items backend CRUD shortcuts to immediately delete or edit the item without searching it in backend > Useful!

Or a end user could display some seo useful link, for example to PageSpeed Insight which will directly be linked to the current page to perform the speed test immediately (I'm working on a admin bar add-on to provide some SEO useful link like that).

And again, all these links could be blocked my the end user with the admin bar settings shortcut.

___________
I hope you get my mind: I hope AdminBar will be used by authors for good reasons, and I'll provide when I'll know exactly how I want to do that a way to block the troll links.

But for now: 9 installations, probably only curious end-users. I think I have some time to think about that (I hope no and tomorrow I get 1'000 installations of the admin bar plugin ;p )

Best regards :)

**Comment by Zmove** [comment]
Hello,

Thank you for the answer, however, I'm not sur if it answer correctly my original suggestion, maybe I was not clear.

I just talk about the fact to move the FEME menu to the october settings menu. It's just a small UI Improvement. You can still use permission system to show or not the menu to the end user

See attached screenshot

![image](https://user-images.githubusercontent.com/1314678/82793956-04ab0a80-9e72-11ea-99d2-554ccfcad3f4.png)

**Comment by RomainMazB** [comment]
Hi,
Wow yeah I was totally elsewhere :astonished:

Hmm, yeah it may be a more appropriate place, thanks for the feedback.

I will investigate how to display list there: For now I only displayed Settings model here in my previous plugins.

Will probably push it in the next few weeks, keep an eye on it ;)

**Comment by Zmove** [comment]
Hello,

Thank you for your answer. This page could help, its not a hard task to move to the setting menu.

https://octobercms.com/docs/plugin/settings

**Comment by RomainMazB** [comment]
Thanks for the link, I already have read this part of the docs but it only talks about "single" settings displayed in a single form. What I need with FEME is a full model controller with a list display of registered model to link and then a form to add/edit/delete each of them.

The same list you showed in your screenshot for the errors log.

That's not mentioned in this part of the documentation, I will investigate.

**Comment by PubliAlex** [comment]
It's quite simple in fact, as you already have the model and the controller, you don't have to reinvent the wheel. You just need to remove your code that register the navigation item, and move it to the registerSettings method instead

You can have a good exemple with the [Responsiv Currency plugin](https://github.com/responsiv/currency-plugin).

Particulary the registerSettings() method in the plugin.php file.

plus

Look in the Currencies.php controller, you just need to add a

SettingsManager::setContext(); call, in order to define the active setting item in the left column.

Normally, you don't have to change anything to your model.

I will try to create a PR if you are stuck, but don't have much time ATM :/

**Comment by RomainMazB** [comment]
Thanks for the tip @publiAlex. Thinking about how to do, it becomes pretty logic...

I'll do it on the next pull. I leave the issue open and will close it when submitted.

If you use and like the plugin(s), please post a review in your available short time on the marketplace!

**Comment by RomainMazB** [comment]
[Done](https://github.com/RomainMazB/octobercms-frontend-model-editor/commit/09d726f3df0ec29ce4803c7a213ba0ae55858fd6).

Thanks @Zmove for suggestion and @PubliAlex for the tip. 

Now I know: `registerSettings` is just used to create a link... Thought it would be forcefully bound to a Settings models.
